"""empty message

Revision ID: 00c4e9c39bb4
Revises: 0e5fe68ffb70
Create Date: 2021-10-20 09:37:06.934715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00c4e9c39bb4'
down_revision = '0e5fe68ffb70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sociedad', sa.Column('nroExpediente', sa.Integer(), nullable=True))
    op.add_column('sociedad', sa.Column('estampillado', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sociedad', 'estampillado')
    op.drop_column('sociedad', 'nroExpediente')
    # ### end Alembic commands ###
