"""empty message

Revision ID: 05f464811a87
Revises: 6e03c7b37882
Create Date: 2021-10-13 22:57:41.162899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05f464811a87'
down_revision = '6e03c7b37882'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    op.drop_table('usuario_tiene_rol')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario_tiene_rol',
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rol_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], name='usuario_tiene_rol_rol_id_fkey'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name='usuario_tiene_rol_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('usuario_id', 'rol_id', name='usuario_tiene_rol_pkey')
    )
    op.create_table('usuario',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('enabled', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='usuario_pkey')
    )
    # ### end Alembic commands ###
