"""empty message

Revision ID: 19fdf2989821
Revises: a952865d1e3b
Create Date: 2021-11-25 12:32:38.382411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19fdf2989821'
down_revision = 'a952865d1e3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sociedad', sa.Column('pais', sa.String(), nullable=True))
    op.add_column('sociedad', sa.Column('estado', sa.String(), nullable=True))
    op.add_column('sociedad', sa.Column('continente', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sociedad', 'continente')
    op.drop_column('sociedad', 'estado')
    op.drop_column('sociedad', 'pais')
    # ### end Alembic commands ###
