"""empty message

Revision ID: 22acc8bcaf93
Revises: 05f464811a87
Create Date: 2021-10-15 01:28:49.647448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22acc8bcaf93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    op.add_column('sociedad', sa.Column('caseId', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sociedad', 'caseId')
    op.create_table('usuario',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('enabled', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='usuario_pkey')
    )
    # ### end Alembic commands ###
