"""sth

Revision ID: 470e4dfb8e4a
Revises: c3c8f75bf589
Create Date: 2021-10-19 08:43:31.827941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '470e4dfb8e4a'
down_revision = 'c3c8f75bf589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('sociedad', sa.Column('caseId', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sociedad', 'caseId')
    op.create_table('rol_tiene_permiso',
    sa.Column('rol_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permiso_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permiso.id'], name='rol_tiene_permiso_permiso_id_fkey'),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], name='rol_tiene_permiso_rol_id_fkey'),
    sa.PrimaryKeyConstraint('rol_id', 'permiso_id', name='rol_tiene_permiso_pkey')
    )
    op.create_table('permiso',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('enabled', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='permiso_pkey')
    )
    # ### end Alembic commands ###
