"""empty message

Revision ID: 52657d1590a9
Revises: 96b0490cd371
Create Date: 2021-10-21 17:25:01.412890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52657d1590a9'
down_revision = '96b0490cd371'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sociedad', sa.Column('nroExpediente', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sociedad', 'nroExpediente')
    # ### end Alembic commands ###
