"""empty message

Revision ID: 5a3e3c6e8b4e
Revises: 96b0490cd371
Create Date: 2021-10-21 17:58:07.337209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a3e3c6e8b4e'
down_revision = '96b0490cd371'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permiso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sociedad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('estatuto', sa.String(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('domicilio_legal', sa.String(), nullable=True),
    sa.Column('domicilio_real', sa.String(), nullable=True),
    sa.Column('representante', sa.String(), nullable=True),
    sa.Column('correo', sa.String(), nullable=True),
    sa.Column('aceptada', sa.Boolean(), nullable=True),
    sa.Column('comentario', sa.String(), nullable=True),
    sa.Column('caseId', sa.Integer(), nullable=True),
    sa.Column('estampillado', sa.String(), nullable=True),
    sa.Column('estatuto_aceptado', sa.Boolean(), nullable=True),
    sa.Column('comentarioAL', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('socio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_sociedad', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('apellido', sa.String(), nullable=True),
    sa.Column('porcentaje', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rol_tiene_permiso',
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permiso.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.PrimaryKeyConstraint('rol_id', 'permiso_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rol_tiene_permiso')
    op.drop_table('socio')
    op.drop_table('sociedad')
    op.drop_table('rol')
    op.drop_table('permiso')
    # ### end Alembic commands ###
