"""empty message

Revision ID: 82d494d3d2b5
Revises: b6f53a09e150
Create Date: 2021-10-13 16:47:16.228348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82d494d3d2b5'
down_revision = 'b6f53a09e150'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sociedad', sa.Column('aceptada', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sociedad', 'aceptada')
    # ### end Alembic commands ###
