"""empty message

Revision ID: 8eef4b563f36
Revises: 275da74d08fe
Create Date: 2021-10-21 18:18:22.829384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eef4b563f36'
down_revision = '275da74d08fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sociedad', sa.Column('nroExpediente', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sociedad', 'nroExpediente')
    # ### end Alembic commands ###
