"""empty message

Revision ID: a952865d1e3b
Revises: ca9eafb4e776
Create Date: 2021-11-24 20:21:47.463524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a952865d1e3b'
down_revision = 'ca9eafb4e776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sociedad', sa.Column('pais', sa.String(), nullable=True))
    op.add_column('sociedad', sa.Column('estado', sa.String(), nullable=True))
    op.add_column('sociedad', sa.Column('continente', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sociedad', 'continente')
    op.drop_column('sociedad', 'estado')
    op.drop_column('sociedad', 'pais')
    # ### end Alembic commands ###
