"""empty message

Revision ID: b6f53a09e150
Revises: 6ed486693d99
Create Date: 2021-10-05 18:58:07.773529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f53a09e150'
down_revision = '6ed486693d99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('socio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_sociedad', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('apellido', sa.String(), nullable=True),
    sa.Column('porcentaje', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('socio')
    # ### end Alembic commands ###
