"""empty message

Revision ID: ca9eafb4e776
Revises: e7a1cd25e139
Create Date: 2021-11-23 22:23:10.349391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca9eafb4e776'
down_revision = 'e7a1cd25e139'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sociedad', sa.Column('fecha_rechazo', sa.Date(), nullable=True))
    op.add_column('sociedad', sa.Column('qr', sa.Integer(), nullable=True))
    op.add_column('sociedad', sa.Column('drive', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'sociedad', ['nombre'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sociedad', type_='unique')
    op.drop_column('sociedad', 'drive')
    op.drop_column('sociedad', 'qr')
    op.drop_column('sociedad', 'fecha_rechazo')
    # ### end Alembic commands ###
