"""empty message

Revision ID: db41c73ad56b
Revises: e818eecf850d
Create Date: 2021-11-18 12:28:56.810241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db41c73ad56b'
down_revision = 'e818eecf850d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sociedad', sa.Column('fecha_rechazo', sa.Date(), nullable=True))
    op.create_unique_constraint(None, 'sociedad', ['nombre'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sociedad', type_='unique')
    op.drop_column('sociedad', 'fecha_rechazo')
    # ### end Alembic commands ###
