"""empty message

Revision ID: e7a1cd25e139
Revises: db41c73ad56b
Create Date: 2021-11-18 16:11:21.877468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a1cd25e139'
down_revision = 'db41c73ad56b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sociedad', sa.Column('fecha_rechazo', sa.Date(), nullable=True))
    op.create_unique_constraint(None, 'sociedad', ['nombre'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sociedad', type_='unique')
    op.drop_column('sociedad', 'fecha_rechazo')
    # ### end Alembic commands ###
